### ISSUE TITLE
Fast Switch Profiles

### ISSUE THREAD

**Issue by ghost** [claha/movianremote#1]
Taping the current server/ip below to switch between profiles
Please.

**Comment by claha** [comment]
Right now you can swipe left/right to switch between the profiles. Could also be a good idea to switch on tap. I will look into that.

**Comment by ghost** [comment]
or maybe a list to select

**Comment by claha** [comment]
If you want a list you can go to settings and choose. The bottom bar is there for convenient switching between profiles. It would be ugly to popup a list and I don't really see a need for it unless you have 10+ devices running Showtime, which is unlikley.
