### ISSUE TITLE
Show Info/Log Button

### ISSUE THREAD

**Issue by ghost** [claha/movianremote#2]
Please add the "Show Info Button" or Square on the PS3, and also posibly the "Show Log"

**Comment by claha** [comment]
Not really sure what the "Show Info Button" is? From the HTTP API I would guess you are reffering to "ItemMenu", "MediaStats" or "SysInfo"? You can get the "ItemMenu" by longpress on Menu.

**Comment by ghost** [comment]
The long press on menu isnt working for me on 0.0.5

from:
https://showtimemediacenter.com/projects/showtime/wiki/PS3_usage_guide

The label on this site is Show Info, it shows the bar below and a window on the top right corner tiitled Playback Status with file, codec, bitrate, buffer and speed info

it doesnt show the actual menu name but on a ps3 controller the button is Square, on a USB keyboard is F2

**Comment by claha** [comment]
Ok, that is media stats. I will integrate some more buttons for the next release. It's really simple to add a new button if you want to do it by yourself for a quicker fix.

I haven't had any issues with the item menu, maybe you are trying to launch the item menu when there isn't one?
