### ISSUE TITLE
Mismatching package name

### ISSUE THREAD

**Issue by ghost** [claha/movianremote#4]
The build.gradle file uses the old package name while AndroidManifest.xml has been updated with the new one. Which one is the correct one? I'd advise on using the old one, because package names should never change. If they do, they are not the same app and so updates cannot be applied.

**Comment by claha** [comment]
Thanks for pointing tat out, ofcourse it should be the old one. Made a new commit a few miniutes ago

**Comment by ghost** [comment]
Thanks for the quick reply and fix!
