### ISSUE TITLE
please add suggestions for searchbar

### ISSUE THREAD

**Issue by vladislavmega** [claha/movianremote#5]
please add suggestions for searchbar

**Comment by claha** [comment]
Would you like your search history to be saved or is it some default
suggestions you are looking for?

tis 15 sep 2015 17:32 Vladislav notifications@github.com skrev:

**Comment by vladislavmega** [comment]
default keyboard suggestions

**Comment by claha** [comment]
I get the suggestions in the search bar as when i type text messages. So I stil don't get what you are looking for. Please specifiy more

**Comment by claha** [comment]
Movian does not seem to be update anymore, will archive this repository. Feel free to fork it.
